language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: Qp5o35Fu86NfnLD9kf+Rr0IoQNpjULX3WensbkV9pxAih7NbbfeR1KF5F1TMt/9VP20SCh5UoweFRlc0eZBDCKwtAPM9XJiwCaW38IV0gV82rvsRpyvBA3/uKhnwXaYNBSTBBJkWiFL6vol/pQFX3bcM6wyDxF4kjtmYJUQnO38vh7Us3DFmfyyfsbfIBPnySdki0y0H+ONfGTIvCZWsSQBMHbkTJ5K8N0uMhYnHV3Y9S4uqtBMe7vDuxfUpBUuhU0ZRnBGVPnG9X71pA+NkgyMucFK8diBVA5l30BPpM9saRAbdc4El8PddYNJ1HfGf9NE1jDLNXVaAQD76s2OO7cw2vJObEivu7FFlUZso0JseV9GcqR+hnK/+LDwgRuNnj5guvnJE5qfWPEmt8bAQGCTJy4o3DdRTVpSE82v4gyOvmJr8pUMG/+oVlWWUbTYq2c+ly77Gi4Rb/QQUjnsLyOMNoH2LwKX2MD4Gj+IlYxVutjyZVlkJbgDRHCOyV/GQ8gTuHFnF/iv6OPqRlCVutFTsdnrv+kTVeJO/m03ky5Rn8ikFLd0FYBDDqy3mMe113jlWPhfd6sWixqY+EKu0DOXuW7fnrjNjAk64/qofFEYVyUaHw91RwEguAy/meJvL014uY56Lr0GvJ2Ta2vA6iUI83b3fz6EylVXHH1cZAdc=
  app: viewing-party
  on:
    all_branches: true
  run: rails db:migrate
